---
- name: Set-up Camunda
  become: yes
  hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: camunda-installation  
    
  vars_prompt:
    - name: db_password
      prompt: Please provide password for the databank